### ISSUE TITLE
"refseq" and "ensembl" Annotation.bed file  format

### ISSUE THREAD

**Issue by qindan2008** [dieterich-lab/FUCHS#13]
Hi,
(1) I guess the difference between "refseq" and "ensembl" Annotation.bed file  format is that the former contains "NM_" or "NR_" accession number while the latter  doesn't. 
For example, **refseq bed format** is like:
1	67092175	67093604	NR_075077_exon_0_0_1_67092176_r	0	-
1	67096251	67096321	NR_075077_exon_1_0_1_67096252_r	0	-
1	67103237	67103382	NR_075077_exon_2_0_1_67103238_r	0	-
1	67111576	67111644	NR_075077_exon_3_0_1_67111577_r	0	-
1	67113613	67113756	NR_075077_exon_4_0_1_67113614_r	0	-
1	67115351	67115464	NR_075077_exon_5_0_1_67115352_r	0	-
in this condition, -p should be "refseq", -c is "_" and -e is "3"
**ensembl bed format** is like:
1	3630	3913	AT1G01010.1_exon_1_0_1_3631_f	0	+
1	3995	4276	AT1G01010.1_exon_2_0_1_3996_f	0	+
1	4485	4605	AT1G01010.1_exon_3_0_1_4486_f	0	+
1	4705	5095	AT1G01010.1_exon_4_0_1_4706_f	0	+
1	5173	5326	AT1G01010.1_exon_5_0_1_5174_f	0	+
in this condition, -p should be "ensembl", -c is "_" and -e is "2"
**is it right** ?
(2) I have doubt with the output "Sample.exon_counts.bed" file in the "Exon Lengths" column.  Why many exon length equals "1" (like below)?
**Exon Lengths**	**Relative Exon Starts**
1,71,99,126,1	0,764,592,0,834
1,71,238,1	0,343,0,413
1,260,74,80,1	0,333,150,0,592
1,133,1	0,340,604
106,62,31,94	0,622,1045,1393
110,141	0,192
404	0

**Comment by FranziMe** [comment]
Dear qindan2008,

Thanks a lot for your contribution.
(1) more or less. choosing refseq will assume that the first two fields in the name belong to the gene name. (e.g, 'human.xy.exon.3', setting -s '.' and -e 3, the gene name is then taken as human and xy and fused again by the split character '.' > human.xy.) choosing 'ensembl' using the same setting would result in only 'human' as the gene name. 

(2) Exons of length 1 are coerced, if the circRNA starts outside an exon annotation. FUCHS is only able to use annotated exons. I suggest using guided_denovo_circle_structure to reconstruct the actual circle structure. I know the documentation doesn't exist yet, but I am working on it. let me know if you have any questions.
