### ISSUE TITLE
how FUCHS circ handle multiple samples at the same time?

### ISSUE THREAD

**Issue by qindan2008** [dieterich-lab/FUCHS#14]
Dear FranziMe,
If FUCHS can handle multiple samples at the same time , or we can only run samples one by one ?
How can I run multiple samples simultaneously?

**Comment by FranziMe** [comment]
Hi qindan2008,
sorry, currently FUCHS is not able to handle multiple samples. You may start several FUCHS runs at the same time to run the samples simultaneously.
