### ISSUE TITLE
Cannot not find numpy when installing

### ISSUE THREAD

**Issue by Rainkikiki** [dieterich-lab/FUCHS#18]
Hi, Dr JAKOBI,

I download the FUCHS from github and using the install code you provided, however, when I use the command 
" python setup.py install --user"
The process failed for there is lack of "numpy". [I have installed numpy 1.14.0 on linux] I have no idea why this happened, could you please help me?

========
Following is the screen output
-----------
Installed /home/usr/.local/lib/python2.7/site-packages/FUCHS-0.2.0-py2.7.egg
Processing dependencies for FUCHS==0.2.0
Searching for numpy>=0.8.2
Reading http://pypi.python.org/simple/numpy/
Couldn't find index page for 'numpy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for numpy>=0.8.2
error: Could not find suitable distribution for Requirement.parse('numpy>=0.8.2')
======
![image](https://user-images.githubusercontent.com/25833639/35385807-90937904-0204-11e8-88ba-acb019646717.png)

Sincerely,
Rayna

**Comment by tjakobi** [comment]
Dear @Rainkikiki,

thank your for your report. I could not reproduce the error with a fresh install. Did you try the install again to rule any any temporary network failures?

You may also remove the numpy dependency from the setup.py file since you seem to already have it installed. That way the installation should finish correctly.

Cheers,
Tobias

**Comment by Rainkikiki** [comment]
Dear Tobias，

Thanks for your reply for the last problem, however, there is still a problem in DCC.
Since it cannot load numpy, I use the main.py directly.

However, when I ran DCC, the pipeline would suddenly break down and output the screen with
 "Notes:
        (1) When a BAM file is used for the A file, the alignment is retained if overlaps exist,
        and exlcuded if an overlap cannot be found.  If multiple overlaps exist, they are not
        reported, as we are only testing for one or more overlaps. "

And the log file will only stops at 
"...
 2018-01-29 21:32:27,122 Start to combine individual circRNA read counts.
 2018-01-29 21:32:27,583 Swap strand information.
 2018-01-29 21:32:27,830 Write in annotation.
 2018-01-29 21:32:27,830 Select gene features in Annotation file.
"

Since I don't know the exact wrong step in order to check my input file, could you please give a help?

Sincerely,

Rayna

**Comment by tjakobi** [comment]
Dear @Rainkikiki,

could you please attach the log file as well as your complete command line which you used to start DCC?

Cheers,
Tobias
