### ISSUE TITLE
Check for R dependency before program start

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/FUCHS#6]
FUCHS uses R to plot some graphs, cluster, etc..
However, you can start the program, run it for hours (if not days) to see it
die because the R dependency is not satisfied.

**Comment by FranziMe** [comment]
Okay, I have noted it and will implement it as soon as I get some time. Thank you

**Comment by tjakobi** [comment]
Just to add this, the R scripts them self are checking and installing their dependencies.
We just have to include a check for the R binary in the setup script.
