### ISSUE TITLE
guided_denovo vs denovo script

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/FUCHS#7]
Two problems about
denovo_circle_structure_parallel
and
guided_denovo_circle_structure_parallel

1) Relative paths are not handled.

2) Command line arguments differ between the two
usage: denovo_circle_structure_parallel [-h] [-c NUM_CPUS] [--tmp TMP_FOLDER]
                                        folder sample_name
usage: guided_denovo_circle_structure_parallel [-h] -I INPUTFOLDER -N SAMPLE
                                               [-A ANNOTATION] [-c NUM_CPUS]
                                               [-T TMP_FOLDER]

**Comment by tjakobi** [comment]
As far as I know guided_denovo_circle_structure_parallel is the maintained version (that does guided and unguided), may be it would make sense to remove the old  denovo_circle_structure_parallel implementation. What do you thing @FranziMe?

**Comment by CDieterich** [comment]
Mmh.. dont think so.
There are only two bed files (bed6 and bed12) as output and no way to toggle between guided and unguided.

**Comment by tjakobi** [comment]
If I remember correctly guided mode was implicitly toggled by supplying an annotation, the file names however did not change. The source code of both files is largely identical.

**Comment by FranziMe** [comment]
denovo is depricated. I will however adjust the guided_denovo output file names based on if the annotation was supplied and unsuported regions were inferred from annotation. While fixing that, I will also fix the relative paths

**Comment by CDieterich** [comment]
Running it today.. it seems that -A annotation is required.

**Comment by FranziMe** [comment]
Fixed it. guided_denovo will perform both, guided and unguided depending on if an annotation file was supplied or not. The output files will be called _exon_chain_inferred_[12/6].bed if the annotation file was supplied and _exon_chain_[12/6].bed if no annotation was supplied. It also works with relative paths now. the script 'denovo_circle_structure_parallel.py' was removed to avoid confusions.
