### ISSUE TITLE
bug in mate_status.txt output

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/FUCHS#9]
I have run FUCHS [https://github.com/dieterich-lab/FUCHS/commit/ec9fd7218254da32d9764052617547491d38797e](url)
on our long RNA-seq data sets.

The mate status (e.g. 1746_A.mate_status.txt) of all reads is undefined.

**Comment by FranziMe** [comment]
How did you merge the chimeric.sam files? I ran the same sample and only two circRNAs have one undefined read

**Comment by CDieterich** [comment]
Bummer !

I merged the linear BAM files instead of the Chimeric BAM files. Sorry.
